# Generated by Django 6.1.1 on 2026-10-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UberApp', '0002_ridebooking_user'),
    ]

    operations = [
    ]
